### ISSUE TITLE
HTML report does not include CVSS Score and CVE number. No Place for Remediation of Vuln

### ISSUE THREAD

**Issue by AdmiralGaust** [kac89/vulnrepo#114]
Few fields related to Issues are not reflecting into the HTML report. The CVE number and CVSS score are not getting printed in the report. Also, I want to have Issue Remediation field for all the issues reported. Can you pls check and help in this regard? It would be nice if you can also provide some information on how to customize the reports. My Overall experience is good with this tool. Just want a few addition of features.

**Comment by kac89** [comment]
Hi @AdmiralGaust thanks for msg. I fix missing cve/cvss field in HTML report. Regarding remediation field, you can use Description field for that, just I want to avoid adding another textarea field.
