### ISSUE TITLE
TypeScript Error on new install

### ISSUE THREAD

**Issue by Etmea** [kac89/vulnrepo#16]
Not sure if this was just my not being familiar with Angular or not, but got this after a fresh clone during the build.
```
$ ng build
ERROR in The Angular Compiler requires TypeScript >=3.4.0 and <3.6.0 but 3.9.5 was found instead.
```

I just checked for which version was specified and back revd TypeScript to 3.5.3 and everything compiled and ran great, but figured you might want to be aware.
```
$ cat yarn.lock
....
typescript@3.5.3:
  version "3.5.3"
  resolved ...
  integrity ...

typescript@^3.4.5:
  version "3.9.5"
  resolved ...
  integrity ...
....
```

**Comment by wckd-online** [comment]
Oh and thank you for all the hard work, awesome app man!

**Comment by kac89** [comment]
Hi @Etmea thank you for report! 

For angular 8 typescript version should be 3.4. I think migration to angular 9 should solve this.
