### ISSUE TITLE
Production Build with different base-href not loading vuln-list

### ISSUE THREAD

**Issue by cathedrall** [kac89/vulnrepo#2]
Hi,

I have built the application using the `ng build --base-href <my base href> --prod` and after installing the application in my proper base-href everything appears to work except the vuln-list. Upon clicking the Vuln-List link, it just loads forever, an upon entering findings, no matching vulns are found. 

I suspect this is a pathing issue where vulns.json located in the <base-href>/assets directory is not being parsed. Also, when attempting to add a custom issue, the add button does not work. 

Any suggestions on proper build flags that might fix this? Or is this a deeper JS issue that needs to be fixed? 

I also wanted to say that this is great work so far. I've tried many open source vulnerability management projects but I really like this one because of the clean interface and workflow. It's simple, effective and doesn't making documenting issues found a hassle, which too many projects do. 

Thanks, and keep up the good work.

**Comment by kac89** [comment]
Hi @cathedrall thank you for contact. 

Can you please try run just for test (no slash at the end):

`ng serve --base-href /app`

For me its working OK, can you confirm? When I run --base-href /app/ not working :)

**Comment by cathedrall** [comment]
@kac89 Thanks for responding so quickly. 
So, yes it appears 
`ng serve --base-href /app` 

works but my original question was building a production app via 
`ng build --base-href /app --prod` which does not work.

**Comment by kac89** [comment]
For me `ng build --base-href /app --prod` seems working fine. Question on what server do you want this to deploy? 

If you use apache2 server, there need to be added .htaccess file. Try https://angular.io/guide/deployment#fallback-configuration-examples

**Comment by cathedrall** [comment]
So right now I'm using a simple ruby http server.
When I build it, I see `vulnrepo-app` in the `/dist` directory, do you rename that directory to `/app` when moving it your web server root?

**Comment by kac89** [comment]
`vulnrepo-app` should be your root directory:
`folderDir = settings.public_folder + '/dist/vulnrepo-app'`

You shouldn't change folder name to /app, when you build --base-href /app, then application should move you to domain/app/home.html

**Comment by cathedrall** [comment]
Awesome, I think you've determined it's a problem on my end, so I'll close this out. 
Thanks again for making such a great app!
