### ISSUE TITLE
Module Build Failed

### ISSUE THREAD

**Issue by bricekh2** [kac89/vulnrepo#210]
I am having a hell of a time installing both with docker-compose and ng. Currently on Ubuntu 22.0.4 but also tried Kali. Any advice for an easier install is appreciated!

ng errors consist of : Error: Can't resolve '~material-design-icons/iconfont/material-icons.css' in '/home and also HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '~material-design-icons/iconfont/material-icons.css' in '/home

docker-compose errors:
Step 5/10 : RUN npm i --force
 ---> Running in 8d0fc96aa30f
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @angular/flex-layout@14.0.0-beta.41
npm WARN Found: @angular/cdk@15.1.0
npm WARN node_modules/@angular/cdk
npm WARN   @angular/cdk@"^15.1.0" from the root project
npm WARN   1 more (@angular/material)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @angular/cdk@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm WARN node_modules/@angular/flex-layout
npm WARN   @angular/flex-layout@"^14.0.0-beta.40" from the root project
npm WARN 
npm WARN Conflicting peer dependency: @angular/cdk@14.2.7
npm WARN node_modules/@angular/cdk
npm WARN   peer @angular/cdk@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm WARN   node_modules/@angular/flex-layout
npm WARN     @angular/flex-layout@"^14.0.0-beta.40" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @angular/flex-layout@14.0.0-beta.41
npm WARN Found: @angular/common@15.1.0
npm WARN node_modules/@angular/common
npm WARN   @angular/common@"^15.1.0" from the root project
npm WARN   7 more (@angular/cdk, @angular/forms, @angular/material, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @angular/common@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm WARN node_modules/@angular/flex-layout
npm WARN   @angular/flex-layout@"^14.0.0-beta.40" from the root project
npm WARN 
npm WARN Conflicting peer dependency: @angular/common@14.2.12
npm WARN node_modules/@angular/common
npm WARN   peer @angular/common@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm WARN   node_modules/@angular/flex-layout
npm WARN     @angular/flex-layout@"^14.0.0-beta.40" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @angular/flex-layout@14.0.0-beta.41
npm WARN Found: @angular/core@15.1.0
npm WARN node_modules/@angular/core
npm WARN   @angular/core@"^15.1.0" from the root project
npm WARN   10 more (@angular/animations, @angular/cdk, @angular/common, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @angular/core@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm WARN node_modules/@angular/flex-layout
npm WARN   @angular/flex-layout@"^14.0.0-beta.40" from the root project
npm WARN 
npm WARN Conflicting peer dependency: @angular/core@14.2.12
npm WARN node_modules/@angular/core
npm WARN   peer @angular/core@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm WARN   node_modules/@angular/flex-layout
npm WARN     @angular/flex-layout@"^14.0.0-beta.40" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @angular/flex-layout@14.0.0-beta.41
npm WARN Found: @angular/platform-browser@15.1.0
npm WARN node_modules/@angular/platform-browser
npm WARN   @angular/platform-browser@"^15.1.0" from the root project
npm WARN   4 more (@angular/forms, @angular/material, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @angular/platform-browser@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm WARN node_modules/@angular/flex-layout
npm WARN   @angular/flex-layout@"^14.0.0-beta.40" from the root project
npm WARN 
npm WARN Conflicting peer dependency: @angular/platform-browser@14.2.12
npm WARN node_modules/@angular/platform-browser
npm WARN   peer @angular/platform-browser@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm WARN   node_modules/@angular/flex-layout
npm WARN     @angular/flex-layout@"^14.0.0-beta.40" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: karma-jasmine-html-reporter@1.7.0
npm WARN Found: jasmine-core@3.7.1
npm WARN node_modules/jasmine-core
npm WARN   dev jasmine-core@"~3.7.1" from the root project
npm WARN   1 more (karma-jasmine)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm WARN node_modules/karma-jasmine-html-reporter
npm WARN   dev karma-jasmine-html-reporter@"^1.7.0" from the root project
npm WARN 
npm WARN Conflicting peer dependency: jasmine-core@4.5.0
npm WARN node_modules/jasmine-core
npm WARN   peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm WARN   node_modules/karma-jasmine-html-reporter
npm WARN     dev karma-jasmine-html-reporter@"^1.7.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: ng2-charts@2.4.3
npm WARN Found: rxjs@7.8.0
npm WARN node_modules/rxjs
npm WARN   rxjs@"^7.8.0" from the root project
npm WARN   8 more (@angular/cdk, @angular/common, @angular/core, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer rxjs@"^6.3.3" from ng2-charts@2.4.3
npm WARN node_modules/ng2-charts
npm WARN   ng2-charts@"^2.4.3" from the root project
npm WARN 
npm WARN Conflicting peer dependency: rxjs@6.6.7
npm WARN node_modules/rxjs
npm WARN   peer rxjs@"^6.3.3" from ng2-charts@2.4.3
npm WARN   node_modules/ng2-charts
npm WARN     ng2-charts@"^2.4.3" from the root project

./src/styles.scss - Error: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '~material-design-icons/iconfont/material-icons.css' in '/app/src'

./src/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '~material-design-icons/iconfont/material-icons.css' in '/app/src'

**Comment by kac89** [comment]
Hi @bricekh2 

I installed latest docker then git clone vulnrepo, then just use cmd: `docker compose up` and its works fine. Build and everything else works. (I assume that docker works the same everywhere, I am thinking here of the environment. I tested on Win11) Make sure you get latest docker, vulnrepo git clone, and then try compose. Let me know your results.

Cheers!

**Comment by bricekh2** [comment]
Still using the current Ubuntu.

Versions Currently Installed:
Docker Version 20.10.12
Docker-Compose 2.3.3

Current errors:
One or more browsers which are configured in the project's Browserslist configuration will be ignored as ES5 output is not supported by the Angular CLI.
Ignored browsers: kaios 2.5, op_mini all
- Generating browser application bundles (phase: setup)...
✔ Browser application bundle generation complete.
✔ Browser application bundle generation complete.

./src/styles.scss - Error: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '~material-design-icons/iconfont/material-icons.css' in '/app/src'

./src/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '~material-design-icons/iconfont/material-icons.css' in '/app/src'


1 error occurred:
	* Status: The command '/bin/sh -c npm run build -- -c production' returned a non-zero code: 1, Code: 1

**Comment by bricekh2** [comment]
npm version 9.5.1

**Comment by bricekh2** [comment]
You can close this issue. I believe the issue was related to cache. Initially Ubuntu had docker compose 1.29. When I upgraded it to 2.3.3 and ran the app it must have been pulling data from cache and failing. I completely removed Vulnrepo, did another git clone, ran docker compose up and it now appears to be working.

One final question, I want to add a section for "Remediation". Would you have instructions on properly adding this permanently rather then adding HTML code on the fly?

**Comment by kac89** [comment]
Thanks for info!

1. "I want to add an option for "Remediation" for each vulnerability": There is no dedicated field for remediation because remediations are mostly linked in reference field, so as not to duplicate content there is no remediation field. But you can use description field, also if you import issues from scanner that have remediations should be auto added to description (like import issues from nessus scanner) or just make fork and edit code and change what you need. But the simple way is just to use Description field.

2. Add custom issues, for now I recommend edit json: https://github.com/kac89/vulnrepo/blob/master/src/assets/vulns.json there are linked by default as a VULNREPO template.

**Comment by bricekh2** [comment]
Understood.

Once I add to the vulns.json file, should docker compose down and then docker compose up then add the new edits?

**Comment by kac89** [comment]
You can edit vulns.json any time. Just close add issue dialog and open again in vulnrepo this will reload list.

**Comment by bricekh2** [comment]
![2023-02-23_16-45](https://user-images.githubusercontent.com/56800496/221047915-083a9709-553e-4479-ae31-fa83f72ca57e.png)
Doesnt appear in the list. It also is not showing in the template list either. That list is still at 42.

**Comment by kac89** [comment]
Check your json syntax. I see on screen missing comma at end of ref param.

**Comment by bricekh2** [comment]
![2023-02-24_09-01](https://user-images.githubusercontent.com/56800496/221211731-4e228d83-ed62-44ff-8809-341371320356.png)
Fixed but results are the same. Not appearing in the search list or the template list.

**Comment by bricekh2** [comment]
I have one location on this machine that contains vulns.json and its vulnrepo/src/assets and thats what I am editing.

**Comment by bricekh2** [comment]
Here is what finally worked for me:

1. docker compose down
2. Edit the vulnrepo/src/assets/vulns.json file.
3. docker compose up --build (this takes more then 8 minutes to complete)
Now I see the change.
