### ISSUE TITLE
Stop Working when upload a xml file in nmap format

### ISSUE THREAD

**Issue by TUTARI-LATAM** [kac89/vulnrepo#223]
Stop working when try upload a file XML from NMAP

**Comment by kac89** [comment]
Hi @TUTARI-LATAM,

Can you provide nmap cli command with arguments/flags that you use?

**Comment by TUTARI-LATAM** [comment]
nmap -T4 -A -v 192.168.100.0/24 192.168.101.0/24 10.0.0.0/24 192.168.15.0/24
attach a example of xml 
[https://send.bitwarden.com/#YAGvx5X6VkGWvK_mAWnR-g/1WrhFjHuIEWwLbNyH_a9CQ](url)
7 days deletion

**Comment by kac89** [comment]
THX, I'll check what's going on and come back with this topic.

**Comment by kac89** [comment]
The problem here is performance, the whole project only runs in the browser so there is a limitation here.

it is difficult to import 1024 entries, so I added an option by default so that hosts which are not online are not added.

You can try on https://dev.vulnrepo.com/

**Comment by TUTARI-LATAM** [comment]
Great Now can add a xml from nmap, have a expecific way of upload a xml from openvas ?? because say please wait for long time and not upload the data

**Comment by kac89** [comment]
let's close this topic and with openvas please submit a new issue and if possible attach the XML that crashes, this will help me solve the problem quickly.

Cheers!
