### ISSUE TITLE
OPENVAS XML FORMAT UPLOAD stuck please wait...

### ISSUE THREAD

**Issue by TUTARI-LATAM** [kac89/vulnrepo#225]
Hi , recently try upload a openvas format xml but keep in Please Wait for more than a hour ago 
attach a example of xml 

[https://send.bitwarden.com/#1UYVrGZH3kuqP6_nAQMn3A/CNQgOrAtZBiRKC4SNRpkFw](url)

Regards.

**Comment by kac89** [comment]
Hi, I made fix and please keep in mind that better will be import less issues at once. In openvas filter issues by cvss or severity before export to XML, this will speed up the whole import process.
