### ISSUE TITLE
Usability questions

### ISSUE THREAD

**Issue by 0xricksanchez** [kac89/vulnrepo#24]
Hey,
First I'd like to say that this is a cool project!
I just played around with it a little and was wondering a couple of things/noticed a few quirks:

* Would be lovely to have an actual share button to the latest release as a `.pdf` or rendered `.html` version of the report as attaching a plain text/html file to an email is not always conform to a bug reporting workflow (at least from my experience)
* I don't quite seem to understand how attachments work. You can add files and sometimes (at least for me) they show up as a *note* in report, but currently there is no way to download/view the attachments right from the report? That would be very helpful!
  * Also as for this `You can easily attach any file you want to. Screenshot, movie or scanner output in txt.` I'd much rather prefer a downloadable file as I would not wanna bloat a report both in content and size by attaching multiple >1k LoC stack traces or even binary samples. 
* Native export as a `.pdf` would be also very helpful.
* Is a setup with SSL/TLS support on the roadmap?
* An online collab feature (share a link/ID to a report with a colleague and have a go at it) would be hella useful, but for this to happen I assume the storage must be shifted from local browser DB to a persistent and accessible network storage?

This sounds like a lot of nagging but as you already have a solid base for report generation I was wondering what you think about these features.

Cheers

**Comment by kac89** [comment]
First of all, thank you @0xricksanchez  for contact !

a small introduction: the whole project is written in front-end technology and there is no any backend system, the project environment is your browser.

- Would be lovely to have an actual share button to the latest release as a .pdf or rendered .html version of the report as attaching a plain text/html file to an email is not always conform to a bug reporting workflow (at least from my experience)

Yep, thats why you have option for TEXT report version. Puting HTML into mailto link is not possible (RFC 6068).

- I don't quite seem to understand how attachments work. You can add files and sometimes (at least for me) they show up as a note in report, but currently there is no way to download/view the attachments right from the report? That would be very helpful!

- Also as for this You can easily attach any file you want to. Screenshot, movie or scanner output in txt. I'd much rather prefer a downloadable file as I would not wanna bloat a report both in content and size by attaching multiple >1k LoC stack traces or even binary samples.

Thanks for that, you found an bug! :D I've already written an fix for this and improvement (added sha256 file checksum for uploaded files, its live on https://vulnrepo.com/). So let me explain how it works now: all images are always displayed and *.txt files. All other file types will be displayed as a link. If you don't want to display large txt use zip file. 

- Native export as a .pdf would be also very helpful.

A long time ago, I was trying jspdf (to generate PDF) and it wasn't good. I understood that it would be easier and faster to use pdf generation from browser.

- Is a setup with SSL/TLS support on the roadmap?

I don't quite understand the question, project does not use backend, there is no communication when editing or creating a report, you can easly use it on http://localhost/. Let me know if I understood you correctly.

- An online collab feature (share a link/ID to a report with a colleague and have a go at it) would be hella useful, but for this to happen I assume the storage must be shifted from local browser DB to a persistent and accessible network storage?

I'm working on it :)

**Comment by 0xricksanchez** [comment]
> Yep, thats why you have option for TEXT report version.
>  I understood that it would be easier and faster to use pdf generation from browser.

 Fair enough. Just thought being able to share a link that auto-generates a pdf version to a report (especially for management level contacts or similar) looks more professional.

> Thanks for that, you found a bug! :D 

You're welcome! :D

> I don't quite understand the question, project does not use backend, there is no communication when editing or creating a report, you can easly use it on http://localhost/.

Yeah I know as much. But depending on how (hell even if) you plan on implementation a collab feature/mongoDB support it may be easier to set it up as a service somewhere where it may have a backend too. I may have thought too far ahead (or too complicated for that matter)

> I'm working on it :)

Awesome!

**Comment by kac89** [comment]
Thanks!
About collab, my plan is to create own API, some auth and write/read encrypted reports on remote API, for now. then we'll see if it makes sense. I count you will check it out yourself!

I'm closing issue now.
Cheers
