### ISSUE TITLE
[+] create new report: ERROR

### ISSUE THREAD

**Issue by Divinemonk** [kac89/vulnrepo#242]
Hey;
I'm not able to create a new report!

I have tried creating several times but its says `Your reports list is empty.`

I also create a `profile` still the same!!!

**Comment by kac89** [comment]
Hi @Divinemonk,

Which browser did you use? 
try on latest release FF/chrome

**Comment by Divinemonk** [comment]
I'm using firefox version `114.0.2 (64-bit)` in private browsing mode!
I'm guessing private window is problem!

**Comment by Divinemonk** [comment]
Okay it is working in normal/non-incognito window/mode!
still don't understand reason for not working in private browsing!

But thank you for such amazing tool :)

**Comment by kac89** [comment]
Hi @Divinemonk 

I added fix commit to alert when indexeddb is not available in browser (error console in browser)

Thanks for reporting an issue and cheers!
