### ISSUE TITLE
Broken Report after downloading (HTML format)

### ISSUE THREAD

**Issue by Divinemonk** [kac89/vulnrepo#244]
I wrote a report & downloaded it, when I saw HTML file the code was broken; 
![image](https://github.com/kac89/vulnrepo/assets/82360546/5d31f2da-cbbd-4bef-a074-e6db1ce08dd5)
(basic/default starting template was present & not broken)

<br>

And the report itself executes the javascript alert I used in an issue;
![image](https://github.com/kac89/vulnrepo/assets/82360546/8ca901bd-4604-474d-92c3-016b44c89c34)
(this is when i reloaded, but same goes when opened for first time)

<br>

I presume that happened because of something I wrote in an issue (inside a code block);
![image](https://github.com/kac89/vulnrepo/assets/82360546/a53c97f1-2a10-43be-912d-21c3d5d7edb3)

<br>

> This could be potentially harmful, as if someone trust our report and opens it that has malicious payload in it - they could be infected

I think filtering all inputs (as string) could solve the issue :)
Thank you!!

**Comment by kac89** [comment]
Hi again @Divinemonk !! Thanks for report.

I made fix, please retest and let me know your results.

Cheers!

**Comment by Divinemonk** [comment]
Nope!

I updated the repo
![image](https://github.com/kac89/vulnrepo/assets/82360546/8cd8c1b8-ba49-4f42-9f42-043218122a8f)

<br>

(update comfimation)
![image](https://github.com/kac89/vulnrepo/assets/82360546/4996bce8-ed6c-449e-8474-780453c6ee7a)

<br>

But still same XSS and Broken report!

**Comment by kac89** [comment]
Hi,

Its probably cache issue. Clear cache. Try check https://vulnrepo.com here is latest code version.

For me it works fine.

**Comment by Divinemonk** [comment]
Yup! 
Working well now - thankyou :)
