### ISSUE TITLE
Running on specified host

### ISSUE THREAD

**Issue by nauliajati** [kac89/vulnrepo#29]
Hi, i had a problem when i try to run serve in difference host, example i want to run with **192.168.1.100** address: **ng serve --host 192.168.1.100**, it's successfully listening on, but when i access it on browser it's not running at all. Also i have modify host in /node_modules/@angular/cli/lib/config/schema.json (_with 0.0.0.0 address_), but didn't fix. Can u guide me to solve this issue? Thanks. :smiley:

**Comment by kac89** [comment]
Hello @nauliajati thanks for contact! I check --host options and it looks like it works for me (tested on windows 10). Maybe try:

> Binding this server to an open connection can result in compromising your application or 
> computer. Using a different host than the one passed to the "--host" flag might result in
> websocket connection issues. You might need to use "--disableHostCheck" if that's the    
> case.

Also check if firewall not blocking ng.

Regards
