### ISSUE TITLE
vulns.json update for OWASP Mobile TOP 10 - Pull Request

### ISSUE THREAD

**Issue by chevonmdphillip** [kac89/vulnrepo#3]
Hi, there it would be great to add all the OWASP Mobile TOP 10 vulnerability issues to the vulns.json file. If you can create a development branch I can take that on and submit a pull request for it. 

https://owasp.org/www-project-mobile-top-10/

I would love to contribute some time to this project. It has a lot of potential.

**Comment by kac89** [comment]
Hi @chevonmdphillip thank you for contact. I created a "dev" branch so now you can submit a pull request. Please use vulns.json only for specific issue/bug/vuln like in file not for group of issues. I am currently working on "Auditor Mode" that will give option to choice a "methodology" (ASVS, mobile ASVS, TOP 10 Mobile etc...) and researcher can step by step review a target requirements, report issues and put summary in final report. 

Regards

**Comment by chevonmdphillip** [comment]
Hey, @kac89 for some reason I can't create a pull request for this issue? Something I'm missing on my end?

**Comment by kac89** [comment]
@chevonmdphillip I think you can link issue after pull request, idk :D

**Comment by chevonmdphillip** [comment]
@kac89 I added four commonly mobile vulnerabilities. Let me know if they look good to merge into master? #4

**Comment by chevonmdphillip** [comment]
@kac89 should we close?
