### ISSUE TITLE
CVE search not working

### ISSUE THREAD

**Issue by ic3-neo** [kac89/vulnrepo#410]
Hello,

The CVE issue adding funtion is not working in web pentestreports.com because of domain **api.vulnrepo.com** is not resolving to any IP

![image](https://github.com/user-attachments/assets/f788dd07-6873-4419-9160-fa363d731145)

![image](https://github.com/user-attachments/assets/6ac78284-a65e-4621-a2e6-157eda573b2b)

**Comment by kac89** [comment]
Hi,

You probably use old vulnrepo version. I do check now latest and works fine. https://vulnrepo.com/

**Comment by kac89** [comment]
and I'm not a owner of pentestreports.com, so I'm not able to upgrade there. In the future use https://vulnrepo.com/ or own local instance.

Cheers!

**Comment by ic3-neo** [comment]
Sorry just found that page and didn't know it was not the original one

![image](https://github.com/user-attachments/assets/73f669d8-3cdd-42c5-b7c7-0a92fd047f73)

And yeah your page is working as a charm, and has more features so of course I will use yours as is the legit one ;) thanks for letting me know :)
