### ISSUE TITLE
[Request] A few things to make it better

### ISSUE THREAD

**Issue by Darkcast** [kac89/vulnrepo#67]
First of all great work guys, I hope you are doing well. 
I have to say that this is by far the best and simplest reporting software ive seen in a while. 
a few things that could make the project better in my oppinion would be,

- The ability to add custom fields in the issues tab 
- The ability to customize the report 
- The ability to set the size of the logo in the report so it doesnt take whole width of the report 
- The ability to remove the social and website links from the report but leaving the name and email 
- The ability to save presets like use dark theme for the report, dont show researcher etc. 

Thank you for all you hardwork and hope you keep up the good work.

**Comment by kac89** [comment]
Hi @Darkcast 
Thank you very much for contact, I think it will not be a problem to add your suggestions. I will plan everything and let you know when the change takes effect.

Regards

**Comment by Darkcast** [comment]
Thank you sir, 
hope you have a great day :)
