### ISSUE TITLE
[Enhancement] Add mongodb support for adding vulnerability entries. 

### ISSUE THREAD

**Issue by chevonmdphillip** [kac89/vulnrepo#8]
@kac89 Taking a deeper look into the back-end code I was wondering if you would be open to implementing a mongodb hosted somewhere to enter vulnerabilities via that way instead of the vulns.json file? Hence the application can pull from that remote or local mongodb? Leaving room for scalability?

However, this might require an a"Admin" interface to enter vulns from the UI into the database. 

Thanks,
Chevon

**Comment by kac89** [comment]
I was thinking about this and not just in the context of vulns.json but whole user data, (reports, vulns.json, etc..) 
this is a natural way to enable work on remote resources, and mongodb is probably one of the best to start. 

I have it on my todo list :)
